/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.tlf.guicompilador.vista.gui;

import co.edu.eam.tlf.analizadorlexico.main.Compilador;
import co.edu.eam.tlf.analizadorlexico.modelo.SimboloLexico;
import co.edu.eam.tlf.analizadorsintactico.main.AnalizadorSintactico;
import co.edu.eam.tlf.guicompilador.vista.controlador.ControladorCompilador;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author user
 */
public class VentanaEditor extends javax.swing.JFrame {

    /**
     * Compilador.
     */
    private ControladorCompilador controlador;

    /**
     * COdigo actual.
     */
    private String codigo;

    /**
     * Creates new form VentanaEditor
     */
    public VentanaEditor() {
        initComponents();
        controlador = new ControladorCompilador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCorrer = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolDerivacion = new javax.swing.JTree();
        editorCodigo = new co.edu.eam.tlf.guicompilador.vista.util.JCodeEditor();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taConsola = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemNuevo = new javax.swing.JMenuItem();
        mnuItemGuardar = new javax.swing.JMenuItem();
        mnuItemAbrir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItemCOrrer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.PNG"))); // NOI18N
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir.PNG"))); // NOI18N
        btnAbrir.setFocusable(false);
        btnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbrir);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.PNG"))); // NOI18N
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correr.PNG"))); // NOI18N
        btnCorrer.setFocusable(false);
        btnCorrer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorrer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCorrer);

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jScrollPane1.setViewportView(arbolDerivacion);

        jSplitPane2.setLeftComponent(jScrollPane1);
        jSplitPane2.setRightComponent(editorCodigo);

        jSplitPane1.setTopComponent(jSplitPane2);

        taConsola.setColumns(20);
        taConsola.setRows(5);
        jScrollPane3.setViewportView(taConsola);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consola", jPanel1);

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo Lexema", "Lexema", "Fila", "Columna"
            }
        ));
        jScrollPane2.setViewportView(tablaTokens);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lexemas", jPanel2);

        jSplitPane1.setRightComponent(jTabbedPane1);

        jMenu1.setText("File");

        mnuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.PNG"))); // NOI18N
        mnuItemNuevo.setText("Nuevo");
        mnuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemNuevo);

        mnuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.PNG"))); // NOI18N
        mnuItemGuardar.setText("Guardar");
        mnuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemGuardar);

        mnuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abrir.PNG"))); // NOI18N
        mnuItemAbrir.setText("Abrir");
        mnuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemAbrir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Run");

        mnuItemCOrrer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnuItemCOrrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correr.PNG"))); // NOI18N
        mnuItemCOrrer.setText("Ejecutar Codigo");
        mnuItemCOrrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCOrrerActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemCOrrer);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemGuardarActionPerformed
        // TODO add your handling code here:
        btnGuardarActionPerformed(evt);

    }//GEN-LAST:event_mnuItemGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if (!editorCodigo.getTextArea().getText().equals(codigo)) {
            int opc = JOptionPane.showConfirmDialog(null, "Desea guardar el archivo?");
            if (opc == JOptionPane.YES_OPTION) {
                btnGuardarActionPerformed(evt);
            }
        }
        codigo = "";
        editorCodigo.getTextArea().setText("");
        archivo = null;

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void mnuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemAbrirActionPerformed
        // TODO add your handling code here:
        btnAbrirActionPerformed(evt);
    }//GEN-LAST:event_mnuItemAbrirActionPerformed

    private void mnuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNuevoActionPerformed
        // TODO add your handling code here:
        btnNuevoActionPerformed(evt);
        setTitle("");
    }//GEN-LAST:event_mnuItemNuevoActionPerformed

    private void mnuItemCOrrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCOrrerActionPerformed
        // TODO add your handling code here:
        btnCorrerActionPerformed(evt);
    }//GEN-LAST:event_mnuItemCOrrerActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        btnNuevoActionPerformed(evt);
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            archivo = fileChooser.getSelectedFile();
            try (BufferedReader lector = new BufferedReader(new FileReader(archivo));) {

                String linea = "";
                while ((linea = lector.readLine()) != null) {
                    codigo += linea + "\n";
                }
                editorCodigo.getTextArea().setText(codigo);
                setTitle(archivo.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(VentanaEditor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnAbrirActionPerformed
    private File archivo;
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (archivo == null) {
            JFileChooser fileChooser = new JFileChooser();
            if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                archivo = fileChooser.getSelectedFile();

            }
        }
        guardarArchivo(archivo);
    }//GEN-LAST:event_btnGuardarActionPerformed
    /**
     * Metodo para almacenar archivos.
     *
     * @param archivo
     */
    private void guardarArchivo(File archivo) {
        try (PrintStream salida = new PrintStream(archivo);) {
            salida.print(editorCodigo.getTextArea().getText());
            codigo = editorCodigo.getTextArea().getText();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrerActionPerformed
        // TODO add your handling code here:
        String parsed = controlador.ejecutar(editorCodigo.getTextArea().getText());
        System.out.println(parsed);

        DefaultTableModel dtm = (DefaultTableModel) tablaTokens.getModel();
        dtm.setRowCount(0);
        for (SimboloLexico simbolo : controlador.getTokens()) {
            dtm.addRow(new Object[]{simbolo.getTipo(), simbolo.getLexema(), simbolo.getFila(), simbolo.getColumna()});
        }

        taConsola.setText(controlador.getTextoConsola().toString());
        //DefaultMutableTreeNode dmtn = new DefaultMutableTreeNode(controlador.getRaiz());
        arbolDerivacion.setModel(new DefaultTreeModel(controlador.getRaiz()));


    }//GEN-LAST:event_btnCorrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolDerivacion;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCorrer;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private co.edu.eam.tlf.guicompilador.vista.util.JCodeEditor editorCodigo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuItemAbrir;
    private javax.swing.JMenuItem mnuItemCOrrer;
    private javax.swing.JMenuItem mnuItemGuardar;
    private javax.swing.JMenuItem mnuItemNuevo;
    private javax.swing.JTextArea taConsola;
    private javax.swing.JTable tablaTokens;
    // End of variables declaration//GEN-END:variables
}
